### ISSUE TITLE
二次元配列！？

### ISSUE THREAD

**Issue by Manato313** [Ichii0924/ProjExD#6]
https://github.com/Ichii0924/ProjExD/blob/06e00d1298a2dd8ff2e0cb959f0eaa6e3b5d89d7/ex02/calc.py#L34

二次元配列を利用してきれいなボタン配置になっていたため、よかったと思う。ただ、空白なボタンが気になった

**Comment by Ichii0924** [comment]
アドバイスを基に修正させていただきました。
