### ISSUE TITLE
なぜE?

### ISSUE THREAD

**Issue by Manato313** [Ichii0924/ProjExD#7]
https://github.com/Ichii0924/ProjExD/blob/236196a286018f7f22d63151f87f4fb9d8a2e760/ex03/maze.py#L30

すみません。Eでスタートに戻るのはなぜでしょうか。何か理由がありますか？あれば教えていただきたいです。

**Comment by Ichii0924** [comment]
トレーサーのEはリコールに割り当てられているのでそれを際限しました。
