### ISSUE TITLE
fが押されたときの機能について

### ISSUE THREAD

**Issue by c0b21057** [Ichii0924/ProjExD#8]
https://github.com/Ichii0924/ProjExD/blob/236196a286018f7f22d63151f87f4fb9d8a2e760/ex03/maze.py#L19
fが押されたときの機能がコメントアウトされているので、消すか理由を書いといてほしい。お願いしします。

**Comment by Ichii0924** [comment]
修正させていただきました。
ちなみに理由についてですが特にありません。
